version: '3'

services:
  web:
    image: marsas/trip-planner-web
    ports:
    - 8082:80

  api:
    image: marsas/trip-planner-api
    ports:
    - 8081:8080
    - 5005:5005
    environment:
      DB_HOST: db
      DB_PORT: 5432

  db:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .database_data:/var/lib/postgresql/data
